# ===================================================================
# Spring Cloud Config bootstrap configuration for the "prod" profile
# In prod profile, properties will be overwriten by the ones defined in bootstrap-prod.yml
# ===================================================================

application:
    test:
        message: hello